### ISSUE TITLE
Can't upload paywalls list on some devices iOS / Android

### ISSUE THREAD

**Issue by Artem2001S** [apphud/ApphudSDK-React-Native#62]
Trying to upload paywalls using: 

```
try {
        const paywalls = await ApphudSdk.paywalls();
        console.log(paywalls) // paywalls not fetched (console log don't work, because promise ApphudSdk.paywalls not performed
} catch (err) {
        console.log(err) // catch console log didn't received
}
```

```
    "@apphud/react-native-apphud-sdk": "^2.0.0"
    "react-native": "0.67.1"
```

**Comment by ren6** [comment]
@Artem2001S we apologize for misleading with the method description. ApphudSdk.paywalls()  method returns only if paywalls were already loaded, it doesn't await until they are loaded in current SDK version.
Please kindly use `paywallsDidFullyLoad` listener method of `ApphudSdkListenerEvents` that fires when paywalls are ready to use.

**Comment by ren6** [comment]
@Artem2001S there might be a problem with fetching native store products: SKProduct / ProductDetails.
Please make sure everything is set up correctly as written in [this guide](https://docs.apphud.com/docs/product-hub).
In order to investigate your issue, please send us Xcode / Android Studio logs, enable them by calling ApphudSdk.enableDebugLogs()

**Comment by Artem2001S** [comment]
Problem fixed automatically, no changes made on code side/store configuration side
